[project.urls]
Changelog = "https://github.com/MI4People/Marine_Litter/release-notes"
Documentation = "https://marine_litter.readthedocs.io/"
Homepage = "https://www.mi4people.org/marinelitterdetectionviasatellites"
Issues = "https://github.com/MI4People/Marine_Litter/issues"
Repository = "https://github.com/MI4People/Marine_Litter"

[project]
authors = [{ name = "Denis Dalić", email = "denis.dalic@mi4people.org" }]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
description = "Marine Litter Detection via Satellites"
license-files = ["LICENSE.txt"]
name = "marine-litter"
readme = "README.md"
# Python 3.12.3 is recommended in Docker to keep it simpler for GDAL and CUDA in Ubuntu 24.04 LTS.
requires-python = ">=3.12.3,<3.14"
version = "0.1.2"

dependencies = [
    "gdal @ https://github.com/cgohlke/geospatial-wheels/releases/download/v2025.10.25/gdal-3.11.4-cp312-cp312-win_amd64.whl; python_version=='3.12' and sys_platform == 'win32'",
    "gdal @ https://github.com/cgohlke/geospatial-wheels/releases/download/v2025.10.25/gdal-3.11.4-cp313-cp313-win_amd64.whl; python_version=='3.13' and sys_platform == 'win32'",
    # Linux/macOS: gdal is provided by the system, not uv/pip. Call `sudo apt install -y python3-gdal`,
    # then create venv with `uv venv --python 3.12 --system-site-packages` (Python version must match system gdal).
    "google-cloud-storage",
    "marinedebrisdetector",      # ignore CVE-2025-63396 by torch 2.9.1, see also README.md
    "pydantic-settings",
    "torch==2.9.1+cu130",
    "torchvision==0.24.1+cu130",
    "up42-py>=3",
]

# Best install uv and ruff in addition to Python (globally, not in venv), e.g.
#   - Windows: `winget install -e astral-sh.uv astral-sh.ruff`
#   - macOS: `brew install uv ruff`
#   - Linux: `pipx install uv ruff` (ensure pipx is available before)
# isort and black will be done by ruff.
[dependency-groups]
dev = [
    "mkdocs",
    "mkdocs-material",
    "mkdocs-mermaid2-plugin",
    "pip-tools",              # for readthedocs, see 'docs/requirements.in'
    "pre-commit",
    "pytest-cov",
    "pytest-sugar",
    "ty",
    "uv_build<1.0",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["marine_litter"]

[tool.black]
line-length = 120
skip-magic-trailing-comma = false

[tool.ruff]
# Preferably only specify non-default values (also in later sub-sections),
#   but defaults https://docs.astral.sh/ruff/configuration/ are quite lenient,
#   e.g. lint.select = ["E4", "E7", "E9", "F"]
#   while e.g. McCabe complexity check would be fine.

cache-dir = ".ruff_cache"
include = ["*.py"]
line-length = 120

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
# A     https://docs.astral.sh/ruff/rules/#flake8-builtins-a    # shadowing
# B     https://docs.astral.sh/ruff/rules/#flake8-bugbear-b     # potential bugs, design issues
# C90   https://docs.astral.sh/ruff/rules/#mccabe-c90           # McCabe complexity, s.a. PLR0912
# E/W   https://docs.astral.sh/ruff/rules/#pycodestyle-e-w      # pycodestyle errors/warnings
# F     https://docs.astral.sh/ruff/rules/#pyflakes-f           # pyflakes
# I     https://docs.astral.sh/ruff/rules/#flake8-imports-i     # import sorting rules
# N     https://docs.astral.sh/ruff/rules/#pep8-naming-n        # PEP8 naming
# PERF  https://docs.astral.sh/ruff/rules/#perflint-perf        # performance
# PL    https://docs.astral.sh/ruff/rules/#flake8-pyi-p         # pylint
# Q     https://docs.astral.sh/ruff/rules/#flake8-quotes-q
ignore = [
    "E731", # lambda-assignment
    "F402", # shadows name from outer scope
]
select = ["B", "E", "F", "I", "PERF", "PL", "ANN"]

[tool.ruff.lint.isort]
# use defaults https://docs.astral.sh/ruff/settings/#lintisort

[tool.ruff.lint.per-file-ignores]
"**/tests/**/*.py" = [
    "PLR2004", # magic-value-comparison
    "ANN001",  # missing-type-annotation
    "ANN201",  # missing-type-annotation
]

[tool.ruff.lint.pylint]
# use defaults https://docs.astral.sh/ruff/settings/#lintpysort

[tool.ty.rules]
all = "error"


[tool.pytest.ini_options]
addopts = "--tb=short --cov=src --cov-report=term-missing"
pythonpath = ["src"]
